[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "chromium",
  "nss",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXrandr",
  "xorg.libxcb",
  "libgcc",
  "glib",
  "at-spi2-atk",
  "dbus",
  "cups",
  "expat",
  "libdrm",
  "libxkbcommon",
  "mesa",
  "pango",
  "cairo",
  "alsa-lib"
]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt",
  "python3 -m playwright install chromium"
]

[start]
cmd = "bash start.sh"
